# Site
repository: sproogen/resume-theme


# Google Analytics
google_analytics: G-N5BC4FYSWL

# Personal info
name: evie
title: <3
email:


# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: zamplifies
# linkedin_username: ja
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: Aprons
about_profile_image: 
about_content: | # this will include new lines to allow paragraphs
  Good afternoon, I am Alex and I have a dream. I want to be a househusband will you make this dream come true evie. if you would like to please let me know okie dokie coolio i have work in a couple hours and can't sleep so ye that's kind of a bummer but yk we live we laught we learn etc etc
  

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests some of my other interests and hobbies are:
   -cooking
   -cleaning
   -gymin
   -gardening
   - being a househusband
   - ...
   

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
darkmode: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
