# Site
repository: sproogen/resume-theme
favicon: images/icon.jpg

# Google Analytics
google_analytics: G-N5BC4FYSWL

# Personal info
name: Alexander Antonovich Zamolotskikh
title: Sex With Alex 2021
email: alex@karanagai.com


# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: mr.zamolo
# linkedin_username: ja
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/IMG_5123.jpg
about_content: | # this will include new lines to allow paragraphs
  Good afternoon, I am Alex and I have a dream. Not a silly dream like change the world but quite a simple one. I would like to have sex with you reader.
  This has been a turbulent year for us all dear reader but through my 3 step plan I believe that I can significantly improve your 2021:             
   - Me and you 
   - **Sex**
   - Happiness
  
  As you can see this plan is robust. So at the end of the day you should not ask how Alex can have sex with you but how you can have sex with Alex.
  
  _Sex With Alex 2021_
  
# Projects Section
projects_profile_image: images/download.jpg

# Experience Section


# Education Section
# educaton_title: Education


# Education Section
# educaton_title: Education

# Consumer_Reviews Section
# consumer_reviews_title: About Me

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in sex some of my other interests and hobbies are:
   - Being Cool
   - Gym
   - Speaking 7 languages
   - Attending Applied Maths
   - Being Cool
   - ...
   

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
darkmode: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
