# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Alexander Antonovich Zamolotskikh
title: Senior Sex Man
email: alex@karanagai.com


# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: alex.z77
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/IMG_5123.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Alex and I'm cool. As well as administrating sex I also have experience making children. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: 

# Projects Section
projects_profile_image: images/download.jpg

# Experience Section


# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in sex some of my other interests and hobbies are:
   - Being Cool
   - Gaming
   - Holding doors
   - Owning a log table
   - Attending Applied Maths
   - ![Alex](https://sexwithalex.github.io/images/download.jpg)
   - ...
   

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme
darkmode: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
